language: node_js
node_js:
  - '10.15.0'
cache: yarn

jobs:
  include:
    - name: 'Type Check and Build'
      script:
        # Includes running type checking and build validation tests
        - yarn run build

    - name: 'Lint'
      script:
        - yarn run lint

    - name: 'Check Custom Properties'
      script:
        - yarn run check:custom-properties

    - name: 'Unit Tests'
      script:
        - yarn run test --coverage
        - yarn run codecov

    - name: 'Accessibility Tests'
      script:
        - STORYBOOK_DISABLE_DOCS=1 yarn run storybook:build --quiet
        - node ./scripts/pa11y.js

    # Travis builds on commit and for PR builds (where Travis merges your last
    # commit in a PR into the base branch). There isn't much value uploading info
    # to ShrinkRay/Percy/Chroma for these merge commits because they're not
    # usefully exposed in their UIs. So skip these jobs on PR builds
    - name: 'Shrink Ray'
      if: type != 'pull_request'
      script:
        - node ./scripts/build-shrink-ray.js

    - name: 'Percy'
      if: type != 'pull_request'
      script:
        - yarn run storybook:build --quiet
        - yarn run percy-storybook --build_dir="build/storybook/static"

    - name: 'Chroma'
      if: type != 'pull_request'
      script:
        - yarn run chromatic publish --build-script-name='storybook:build'
