production:
  classification: tier4
npm:
  classification: library
url: https://polaris-react.shopifycloud.com
oncall_url: https://shopify.pagerduty.com/services/PQNFXB1
security:
  data_management:
    contains_pii: false
