name: Compose
description: Used to denote the action of composing a new message.
keywords:
  - compose
  - message
  - write
  - pencil
  - pen
authors:
  - Anthony Menecola
  - Jesse Bennett-Chamberlain
  - Joe Thomas
date_added: 2020-07-13
date_modified: 2023-06-23
exclusive_use:
