name: '@shopify/polaris-icons CI'

on:
  pull_request:
    paths:
      - 'polaris-icons/**'
  push:
    branches: main
    paths:
      - 'polaris-icons/**'

jobs:
  test:
    name: Test with node v${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['14.17.0', '16.13.0']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: ${{ matrix.node_version }}
          cache: yarn

      - uses: actions/cache@v2
        name: Restore cache
        with:
          path: |
            .eslintcache
          key: ${{ runner.os }}-node${{ matrix.node_version }}-test-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-node${{ matrix.node_version }}-test-v1-

      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn type-check
      - run: yarn workspace @shopify/polaris-icons test
