name: '@shopify/polaris CI'

on:
  pull_request:
    paths:
      - 'polaris-react/**'
  push:
    branches: [main, polaris-release]
    paths:
      - 'polaris-react/**'

jobs:
  test:
    name: Test with node v${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['14.17.0', '16.13.0']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: ${{ matrix.node_version }}
          cache: yarn

      - uses: actions/cache@v2
        name: Restore cache
        with:
          path: |
            .eslintcache
            **/*.tsbuildinfo
            polaris-react/.loom
          key: ${{ runner.os }}-node${{ matrix.node_version }}-test-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-node${{ matrix.node_version }}-test-v1-

      - run: yarn --frozen-lockfile
      - run: yarn workspace @shopify/polaris run validate-tokens
      - run: yarn build
      - run: yarn lint
      - run: yarn type-check
      - run: yarn workspace @shopify/polaris run test

  accessibility_test:
    name: 'Accessibility test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - uses: actions/cache@v2
        name: Restore internal build cache
        with:
          path: |
            polaris-react/build-internal/cache
          key: ${{ runner.os }}-node${{ matrix.node-version }}-accessibility-test-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-node${{ matrix.node-version }}-accessibility-test-v1-

      - run: yarn --frozen-lockfile
      - run: yarn workspace @shopify/polaris run storybook:build --quiet
      - run: node ./polaris-react/scripts/accessibility-check.js
        env:
          STORYBOOK_DISABLE_DOCS: 1

  visual_regression_test:
    name: 'Visual regression test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Chromatic git history to track changes
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - uses: actions/cache@v2
        name: Restore internal build cache
        with:
          path: |
            polaris-react/build-internal/cache
          key: ${{ runner.os }}-node${{ matrix.node-version }}-visual-regression-test-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-node${{ matrix.node-version }}-visual-regression-test-v1-

      - run: yarn --frozen-lockfile
      - run: yarn workspace @shopify/polaris run storybook:build --quiet

      - uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: 'main'
          storybookBuildDir: 'polaris-react/build-internal/storybook/static'
          exitZeroOnChanges: true
          exitOnceUploaded: true
