name: Snapshot

on:
  repository_dispatch:
    types:
      - snapshot-release-command

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  snapshot:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Checkout snapshot branch
        run: |
          git checkout -b snapshot
          git reset --hard ${{ github.event.client_payload.pull_request.head.ref }}

      - name: Create release Pull Request or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn version-packages --snapshot snapshot
          publish: yarn release --no-git-tags --snapshot
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
